name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the 'dev' branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH to deploy code on the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step to create backend directory if it doesn't exist, pull code, and install dependencies
      - name: Deploy backend code
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            # Create backend directory if it doesn't exist
            mkdir -p /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/backend

            # Navigate to backend directory and pull latest code
            cd /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/backend || exit
            git pull origin dev

            # Install backend dependencies
            npm install --force
          EOF

      # Step to create frontend directory if it doesn't exist, pull code, and build fronten
      - name: Deploy frontend code
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            # Create frontend directory if it doesn't exist
            mkdir -p /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/frontend

            # Navigate to frontend directory and pull latest code
            cd /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/frontend || exit
            git pull origin dev

            # Install frontend dependencies and build the project
            npm install --force
            npm run build
          EOF

      # Step to move frontend build files to the public directory
      - name: Move frontend build to public folder
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            # Ensure the public folder exists
            mkdir -p /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/public

            # Move build files (not the folder) to the public directory
            rsync -avz --delete /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/frontend/build/ /var/www/vhosts/zaptas.in/mnt/vol-us-1/invoiceworld/public/
          EOF

      # Step to restart Nginx server after deployment
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no root@162.241.149.204 << 'EOF'
            systemctl restart nginx
          EOF
